accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_delete/", views.profile_delete, name="profile_delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("recovery/id/", views.RecoveryIdView.as_view(), name="recovery_id"),
    path("recovery/id/find/", views.ajax_find_id_view, name="ajax_id"),
    # 비밀번호 초기화
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path(
        "post_list_category/<str:slug>/",
        views.post_list_category,
        name="post_list_category",
    ),
    path(
        "post_list_search/<str:search>/",
        views.post_list_search,
        name="post_list_search",
    ),
    path(
        "post_list_tag/<str:tag>/",
        views.post_list_tag,
        name="post_list_tag",
    ),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("<int:pk>/new_comment/", views.comment_new, name="new_comment"),
    path("comment_edit/<int:comment_pk>/", views.comment_edit, name="comment_edit"),
    path(
        # "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
        "comment_delete/",
        views.comment_delete,
        name="comment_delete",
    ),
]

firetube/urls.py
from django.urls import path
from . import views

app_name = "firetube"

urlpatterns = [
    path("video_list/", views.video_list, name="video_list"),
    path(
        "video_list_category/<str:slug>/",
        views.video_list_category,
        name="video_list_category",
    ),
    path(
        "video_list_search/<str:search>/",
        views.video_list_search,
        name="video_list_search",
    ),
    path("<int:pk>/", views.video_detail, name="video_detail"),
    path("<int:pk>/new_comment/", views.comment_new, name="new_comment"),
    path(
        # "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
        "comment_delete/",
        views.comment_delete,
        name="comment_delete",
    ),
]

firetube/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Video(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    video = EmbedVideoField()
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )
    n_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("firetube:video_detail", args=[self.pk])

    @property
    def update_counter(self):
        self.n_count = self.n_count + 1
        self.save()
        return self.n_count

    class Meta:
        ordering = ["-id"]


class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)  # 1:다수는 다수측에 정의
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="firetube_my_author_set",
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return "{}::{}".format(self.author, self.message)

    def get_absolute_url(self):
        return f"{self.video.get_absolute_url()}#comment-{self.pk}"

firetube/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["message"].widget.attrs = {
            "placeholder": "메세지를 입력해 주세요",
            "rows": 3,
            "cols": 60,
        }

firetube/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Video, Comment, Category
from django.core.paginator import Paginator
from .forms import CommentForm
from django.contrib import messages
from django.http import HttpResponse
import json


def video_list(request):
    query = Video.objects.all()
    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Video.objects.all().count()
    no_category_post_count = Video.objects.filter(category=None).count()

    return render(
        request,
        "firetube/video_list.html",
        {
            "video_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


def video_list_category(request, slug):
    if slug != "기 타":
        query = Video.objects.filter(category__name__contains=slug)
    else:
        query = Video.objects.filter(category=None)

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Video.objects.all().count()
    no_category_post_count = Video.objects.filter(category=None).count()

    return render(
        request,
        "firetube/video_list.html",
        {
            "video_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "slug": slug,
        },
    )


def video_list_search(request, search):
    query = Video.objects.filter(
        Q(title__icontains=search) | Q(description__icontains=search)
    )

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Video.objects.all().count()
    no_category_post_count = Video.objects.filter(category=None).count()

    return render(
        request,
        "firetube/video_list.html",
        {
            "video_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "search": search,
        },
    )


def video_detail(request, pk):
    video = get_object_or_404(Video, pk=pk)
    categories = Category.objects.all()
    total_category_post_count = Video.objects.all().count()
    no_category_post_count = Video.objects.filter(category=None).count()
    comment_form = CommentForm()

    return render(
        request,
        "firetube/video_detail.html",
        {
            "video": video,
            "comment_form": comment_form,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


def comment_new(request, pk):
    if request.user.is_authenticated:
        video = get_object_or_404(Video, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.video = video
                comment.save()
                if request.is_ajax():
                    return render(
                        request,
                        "firetube/_comment.html",
                        {
                            "comment": comment,
                        },
                    )
                return redirect("firetube:video_detail", video.pk)
        else:
            comment_form = CommentForm()
    else:
        raise PermissionDenied

    return redirect(
        request,
        "firetube/comment_form.html",
        {
            "comment_form": comment_form,
            "video": video,
        },
    )


# def comment_edit(request, comment_pk):
#     if request.user.is_authenticated:
#         comment = get_object_or_404(Comment, pk=comment_pk)
#         post = comment.post
#
#         if request.method == "POST":
#             comment_form = CommentForm(request.POST, instance=comment)
#             if comment_form.is_valid():
#                 comment = comment_form.save(commit=False)
#                 comment.author = request.user
#                 comment.post = post
#                 comment.save()
#                 return redirect(post.get_absolute_url())
#         else:
#             comment_form = CommentForm(instance=comment)
#     else:
#         raise PermissionDenied
#
#     return render(
#         request,
#         "blog/comment_edit.html",
#         {
#             "comment_form": comment_form,
#             "comment": comment,
#         },
#     )


# @login_required
# def comment_delete(request, comment_pk):
#     comment = get_object_or_404(Comment, pk=comment_pk)
#     if request.user.is_authenticated and request.user == comment.author:
#         comment.delete()
#         messages.success(request, "댓글을 삭제했습니다.")
#         return redirect(comment.video.get_absolute_url())
#     else:
#         raise PermissionDenied


@login_required
def comment_delete(request):
    comment_pk = request.POST.get("comment_pk")
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        data = {
            "comment_pk": comment_pk,
        }
        # messages.success(request, "댓글을 삭제했습니다.")
        return HttpResponse(
            json.dumps(data, cls=DjangoJSONEncoder), content_type="application/json"
        )

    else:
        raise PermissionDenied

firetube/templates/firetube/_comment.html
{#{% load bootstrap5 %}#}
{##}
{#<!-- Comment with nested comments-->#}
{#<div class="d-flex mt-5">#}
{#    <!-- Parent comment-->#}
{#    <div class="flex-shrink-0">#}
{#        <img class="rounded-circle me-3" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>#}
{#    </div>#}
{#    <div class="ms-1">#}
{#        <div class="fw-bold mb-2">{{ comment.author }}#}
{#            <span class="ms-2">#}
{#                {% if comment.created_at == comment.updated_at %}#}
{#                    <small class="text-muted">{{ comment.created_at | date:"Y.m.d H:i"}}</small>#}
{#                {% else %}#}
{#                    <small class="text-muted">{{ comment.updated_at | date:"Y.m.d H:i"}}</small>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}
{#        {{ comment.message | linebreaks }}#}
{#        {% if user.is_authenticated and comment.author == user %}#}
{#                                    <a role="button" class="btn btn-primary" style="font-size: 2.0px" href="{% url "blog:comment_edit" comment.pk %}">수정</a>#}
{#            <a role="button" class="btn btn-danger" style="font-size: 12px" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
{#            {% include "firetube/comment_delete_modal.html" %}#}
{#        {% endif %}#}
{#    </div>#}
{#</div>#}

{% load bootstrap5 %}

<!-- Comment with nested comments-->
<div id="comment-{{ comment.pk }}" class="d-flex mt-5">
    <!-- Parent comment-->
    <div class="flex-shrink-0">
        <img class="rounded-circle me-3" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>
    </div>
    <div class="ms-1">
        <div class="fw-bold mb-2">{{ comment.author }}
            <span class="ms-2">
                {% if comment.created_at == comment.updated_at %}
                    <small class="text-muted">{{ comment.created_at | date:"Y.m.d H:i"}}</small>
                {% else %}
                    <small class="text-muted">{{ comment.updated_at | date:"Y.m.d H:i"}}</small>
                {% endif %}
            </span>
        </div>
        {{ comment.message | linebreaks }}
        {% if user.is_authenticated and comment.author == user %}
{#                                    <a role="button" class="btn btn-primary" style="font-size: 2.0px" href="{% url "blog:comment_edit" comment.pk %}">수정</a>#}
{#            <a role="button" id="comment-pk-deliver" class="btn btn-danger" style="font-size: 12px" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
            <a role="button" class="btn btn-danger" style="font-size: 12px" onclick="commentDelete('{{ comment.pk }}');">댓글삭제</a>
{#            {% include "blog/comment_delete_modal.html" %}#}
        {% endif %}
    </div>
</div>
<span id="comment-pk" style="display: none">{{ comment.pk }}</span>


{#<script type="text/javascript">#}
{#    $(document).ready(function () {#}
{#        $("#comment-pk-deliver").click(function () {#}
{#            var comment_pk = $("#comment-pk").val();#}
{##}
{#            $.ajax({#}
{#                type: "POST",#}
{#                url: "/blog/comment_pk_deliver/",#}
{#                dataType: "json",#}
{#                data: {#}
{#                    'comment_pk': comment_pk,#}
{#                    'csrfmiddlewaretoken': '{{csrf_token}}',#}
{#                },#}
{#                success: function (response) {#}
{#                    console.log("pk를 전달했습니다.")#}
{#                },#}
{#            });#}
{#        })#}
{#    });#}
{#</script>#}

<script type="text/javascript">
    function commentDelete(value) {
        var comment_pk = value;
        var delete_warning = confirm("댓글을 삭제하시겠습니까?");
        if (delete_warning === true) {
            $.ajax({
                type: "POST",
                url: "{% url "firetube:comment_delete" %}",
                dataType: "json",
                data: {
                    'comment_pk': comment_pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function (response) {
                    $("#" + "comment-" + response.comment_pk).remove()
                    {#alert("댓글을 삭제했습니다.")#}
                },
            });
        }
    }
</script>

firetube/templates/firetube/comment_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="CommentDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CommentDeleteModal">댓글 삭제</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span class="fst-italic">정말 삭제하시겠습니까?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{% url "firetube:comment_delete" comment.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

firetube/templates/firetube/comment_edit.html
{% extends "layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <section class="mb-5">
                    <div class="card bg-light">
                        <div class="card-header">
                            <strong>메세지 수정</strong>
                        </div>
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "blog:comment_edit" comment.pk %}">
                                {% csrf_token %}
                                {% bootstrap_form comment_form layout="inline" %}
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
                                    {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock content %}

firetube/templates/firetube/comment_form.html
{#{% load bootstrap5 thumbnail %}#}
{##}
{#<!-- Comments section-->#}
{#<section class="mt-5 mb-5 ms-3">#}
{#    <div class="card bg-light">#}
{#        <div class="card-header">#}
{#            Leave a Comment#}
{#        </div>#}
{#        {% if user.is_authenticated %}#}
{#            <div class="card-body">#}
{#                <!-- Comment form-->#}
{#                <form class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "firetube:new_comment" video.pk%}">#}
{#                    {% csrf_token %}#}
{#                    {% bootstrap_form comment_form layout="inline" %}#}
{#                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">#}
{#                        {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}#}
{#                    </div>#}
{#                </form>#}
{#                {% if video.comment_set.exists %}#}
{#                    {% for comment in video.comment_set.all %}#}
{#                        <!-- Comment with nested comments-->#}
{#                        <div class="d-flex mt-5">#}
{#                            <!-- Parent comment-->#}
{#                            <div class="flex-shrink-0">#}
{#                                <img class="rounded-circle me-3" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>#}
{#                            </div>#}
{#                            <div class="ms-1">#}
{#                                <div class="fw-bold mb-2">{{ comment.author }}#}
{#                                    <span class="ms-2">#}
{#                                        {% if comment.created_at == comment.updated_at %}#}
{#                                            <small class="text-muted">Updated : {{ comment.created_at | date:"Y.m.d H:i"}}</small>#}
{#                                        {% else %}#}
{#                                            <small class="text-muted">{{ comment.updated_at | date:"Y.m.d H:i"}}</small>#}
{#                                        {% endif %}#}
{#                                    </span>#}
{#                                </div>#}
{#                                {{ comment.message | linebreaks }}#}
{##}
{#                                {% if user.is_authenticated and comment.author == user %}#}
{#                                    <a role="button" class="btn btn-primary" style="font-size: 2.0px" href="{% url "blog:comment_edit" comment.pk %}">수정</a>#}
{#                                    <a role="button" class="btn btn-danger" style="font-size: 12px" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
{#                                    {% include "firetube/comment_delete_modal.html" %}#}
{#                                {% endif %}#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                {% endif %}#}
{#            </div>#}
{#        {% else %}#}
{#             <div class="card-body">#}
{#                <a role="button" class="btn btn-outline-dark d-grid" href="{% url "accounts:login" %}" data-toggle="" data-target="#">#}
{#                    <strong class="text-muted">Log in and leave a comment</strong>#}
{#                </a>#}
{#             </div>#}
{#        {% endif %}#}
{#    </div>#}
{#</section>#}


{% load bootstrap5 thumbnail %}

<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-header">
            Leave a Comment
        </div>
        {% if user.is_authenticated %}
            <div class="card-body">
                <!-- Comment form-->
                <form id="post-{{ video.pk }}-comment-form" class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "firetube:new_comment" video.pk%}">
                    {% csrf_token %}
                    {% bootstrap_form comment_form layout="inline" %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
                        {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
                    </div>
                </form>
{#                <div id="post-{{ post.pk }}-comment-list" class="d-flex mt-5"></div>#}
                {% if video.comment_set.exists %}
                    {% for comment in video.comment_set.all %}
{#                  <!-- Comment with nested comments-->#}
{#                    <div class="d-flex mt-5">#}
                        {% include "firetube/_comment.html" %}

{#                        <!-- Parent comment-->#}
{#                        <div class="flex-shrink-0">#}
{#                            <img class="rounded-circle me-3" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>#}
{#                        </div>#}
{#                        <div class="ms-1">#}
{#                            <div class="fw-bold mb-2">{{ comment.author }}#}
{#                                <span class="ms-2">#}
{#                                    {% if comment.created_at == comment.updated_at %}#}
{#                                        <small class="text-muted">Updated : {{ comment.created_at | date:"Y.m.d H:i"}}</small>#}
{#                                    {% else %}#}
{#                                        <small class="text-muted">{{ comment.updated_at | date:"Y.m.d H:i"}}</small>#}
{#                                    {% endif %}#}
{#                                </span>#}
{#                            </div>#}
{#                            {{ comment.message | linebreaks }}#}
{#                            {% if user.is_authenticated and comment.author == user %}#}
{#                                    <a role="button" class="btn btn-primary" style="font-size: 2.0px" href="{% url "blog:comment_edit" comment.pk %}">수정</a>#}
{#                                <a role="button" class="btn btn-danger" style="font-size: 12px" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
{#                                {% include "blog/comment_delete_modal.html" %}#}
{#                            {% endif %}#}
{#                        </div>#}
{#                    </div>#}
                    {% endfor %}
                {% endif %}
            </div>
        {% else %}
             <div class="card-body">
                <a role="button" class="btn btn-outline-dark d-grid" href="{% url "accounts:login" %}" data-toggle="" data-target="#">
                    <strong class="text-muted">Log in and leave a comment</strong>
                </a>
             </div>
        {% endif %}
    </div>
</section>



<script>
    $(function () {
        var form_id = "post-{{ video.pk }}-comment-form";
        $("#" + form_id).submit(function (e) {
            e.preventDefault();

            var options = {
                success: function (responseText, statusText, xhr, $form) {
                    console.group("ajaxSubmit response");
                    console.log(responseText);
                    console.log(statusText);
                    console.log(xhr);
                    console.log($form);
                    console.groupEnd();

                    $("#" + form_id).after(responseText);
                    $("textarea[name=message]").val("");

                    {#$("#" + form_id ).prepend(responseText)#}
                }
            };
            $(this).ajaxSubmit(options);
        });
        console.log("document ready.")

    });
</script>

firetube/templates/firetube/side_widgets.html
{% load bootstrap5 %}

<!-- Side widgets-->
<div class="col-lg-4">
    <!-- Search widget-->
    <div class="card mb-4">
        <div class="card-header">Search</div>
        <div class="card-body">
            <div class="input-group">
                <label for="search-input"></label><input class="form-control" type="text" placeholder="Enter search term..." id="search-input"/>
                <button class="btn btn-secondary" id="button-search" type="button" onclick="searchPost();">Go!</button>
            </div>
        </div>
    </div>

    <!-- Categories widget-->
    <div class="card mb-4">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "firetube:video_list" %}"> 전 체 <span class="float-sm-end">({{ total_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
                {% for category in categories %}
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-2">
                            <li>
                                <a class="text-muted" href="{% url "firetube:video_list_category" category.name %}">{{ category.name }} <span class="float-sm-end">({{ category.video_set.count }})</span></a>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "firetube:video_list_category" "기 타" %}"> 기 타 <span class="float-sm-end">({{ no_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function searchPost(){
        let searchValue = document.getElementById("search-input").value.trim();
        if (searchValue.length > 1) {
            location.href = "/firetube/video_list_search/" + searchValue + "/";
        }
        else {
            alert("검색어(" + searchValue + ")가 너무 짧습니다.")
        }
    }

    document.getElementById("search-input").addEventListener("keydown", function(e)
        {
            if(e.key === "Enter"){
                searchPost()
            }
        });
</script>

firetube/templates/firetube/video_detail.html
{% extends "firetube/post_base.html" %}
{% load bootstrap5 embed_video_tags %}

{#    {% block semi_content %}#}
{##}
{#        <div class="card ms-3">#}
{#            {% video video.video as youtube %}#}
{#                <iframe src="{{ youtube.url }}" name="iframe" allowfullscreen onload="iframe_autoresize(this)" width="100%" height="500px"></iframe>#}
{#            {% endvideo %}#}
{#        </div>#}
{##}
{##}
{#    {% endblock semi_content %}#}

{% block semi_content %}
<!-- Post content-->
    <article class="ms-3 mb-5">
        <!-- video header-->
        <header class="mb-2">
            <!-- video title-->
            <h3 class="mb-1">{{ video.title }}</h3>
            <div class="d-flex text-muted mt-3">
                <div class="flex-grow-1">
                    <span class="badge rounded-pill bg-light" style="color: black; font-size: 14px">
                        <img class="rounded-circle me-1" src="{{ video.author.avatar_url }}" alt="pydenticon_image" style="height: 32px; width: 32px"/>
                        {{ video.author }}
                    </span>
                </div>
                <div>
                    <span class="justify-content-end" style="font-size: 14px">Posted on {{ video.created_at | date:"Y-m-d" }} </span>
                </div>
            </div>
            <hr>

            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-light me-1 mt-1" style="font-size: small;" href="{% url "firetube:video_list" %}"> 목록 </a>
{#                {% if user.is_authenticated and post.author == request.user %}#}
{#                    <a class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" href="{% url "blog:post_update" post.pk %}"> 수정</a>#}
{#                    <a type="button" class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" data-bs-toggle="modal" data-bs-target="#PostDeleteModal"> 삭제</a>#}
{#                    {% include "blog/Post_delete_modal.html" %}#}
{#                {% endif %}#}
        </header>
        <!-- Preview video figure-->
        {% video video.video as youtube %}
            <iframe src="{{ youtube.url }}" name="iframe" width="100%" height="500px" allowfullscreen></iframe>
        {% endvideo %}

        <!-- Post content-->
        <section class="mt-3 mb-2 fw-lighter lh-lg">
            {{ video.description | safe }}
        </section>
    </article>

        <!-- Comments section-->
            {% include "firetube/comment_form.html" %}
            <span style="display: none">{{ video.update_counter }}</span>
{% endblock semi_content %}